module.exports = [
  "LAKEY INSPIRED — Chill Day"
  , "athenswill2 — Chill"
  , "ＦＬＸＸＳＣＨＸＲ — chill"
  , "l over — chill"
  , "Lo'vae TMG4L — Chill"
  , "N/A — CHiLL"
  , "mokiat — Chill"
  , "LoudTech — Chill"
  , "Korgluva — Chill"
  , "REPE_T — Chill"
  , "Red Steel — Chill"
  , "Artist of the Fortnight — Chill"
  , "D.I.M — Chill"
  , "DR. X — Chill"
  , "COSMIC — Chill"
  , "maxno — Chill"
  , "Ari Aung Linn — cHiLL"
  , "Phantrensa the Wicked — Chill"
  , "KurtBeatz' — Chill"
  , "dj fuegs — Chill"
  , "TTR — chill"
  , "XXJØRDAN — Chill"
  , "Pirate Pete — Chill"
  , "Mass Lardage — Chill"
  , "RafaFentanes — Chill"
  , "DirtyKOko — Chill"
  , "D.Brown — Chill"
  , "chilliestpoet — chill"
  , "hungastryke — Chill"
  , "klrr — Chill"
  , "opan — chill"
]